### ISSUE TITLE
需求：希望控制台代码生成增加或修改发送功能

### ISSUE THREAD

**Issue by Peterzhangnoise** [wmn1525/grasscutterTools#5]
每次选好物品后，需要点击复制然后再到控制台粘贴在点击发送按钮，希望添加一个发送功能直接将生成的物品直接发送

**Comment by Peterzhangnoise** [comment]
我看到你代码里面有执行这个，之前就想到了？

**Comment by wmn1525** [comment]
![image](https://user-images.githubusercontent.com/31503298/172129607-d6a08bba-9467-4b7b-b154-08ced58d1d8b.png)
